#!/bin/bash -l

$TTNMAPPER_HOME/processing_scripts/stats_per_device.py
$TTNMAPPER_HOME/processing_scripts/stats_per_application.py
#$TTNMAPPER_HOME/processing_scripts/aggregate_gateways_lastheard.py
$TTNMAPPER_HOME/processing_scripts/aggregate_gateways_details.py
$TTNMAPPER_HOME/processing_scripts/gateway_descriptions.py
#$TTNMAPPER_HOME/processing_scripts/points_to_radar_db.py
$TTNMAPPER_HOME/processing_scripts/circles_all_geojson.py
$TTNMAPPER_HOME/processing_scripts/circles_single.py
#$TTNMAPPER_HOME/processing_scripts/radials_all_geojson.py
#$TTNMAPPER_HOME/processing_scripts/radials_all_geojson_5mdeg.py
#$TTNMAPPER_HOME/processing_scripts/radials_per_gateway_geojson.py
#$TTNMAPPER_HOME/processing_scripts/radials_per_gateway_kml.py
#$TTNMAPPER_HOME/processing_scripts/heatmap_per_gateway_kml.py
$TTNMAPPER_HOME/processing_scripts/radar_db_to_geojson_colour.py
#$TTNMAPPER_HOME/processing_scripts/radar_db_to_geojson_single.py
$TTNMAPPER_HOME/processing_scripts/concave_huls_multi.py
#$TTNMAPPER_HOME/processing_scripts/points_to_radar_db.py --force all
#$TTNMAPPER_HOME/processing_scripts/createDump.py

$TTNMAPPER_HOME/processing_scripts/aggregate_to_db_5mdeg.py
$TTNMAPPER_HOME/processing_scripts/aggregate_to_db.py
